### ISSUE TITLE
Can't resolve './build/Release/ecdh'

### ISSUE THREAD

**Issue by asutula** [torusresearch/eccrypto#33]
I'm trying to use the Biconomy SDK in a Next 13 app (webpack 5 I guess). Getting the error:

``` 
Module not found: Can't resolve './build/Release/ecdh' in '/Users/aaron/Code/textile/studio/node_modules/@toruslabs/eccrypto'

Import trace for requested module:
./node_modules/@toruslabs/eccrypto/index.js
./node_modules/@toruslabs/openlogin/dist/openlogin.cjs.js
./node_modules/@web3auth/openlogin-adapter/dist/openloginAdapter.cjs.js
./node_modules/@biconomy/web3-auth/dist/src/SocialLogin.js
./node_modules/@biconomy/web3-auth/dist/src/index.js
./src/components/login.tsx
```

node --version
v18.12.1
Apple M1 Pro
MacOS Ventura 13.3

I know there are some poyfills that need to be provided if using webpack 5, which I did. I'm not sure if that has anything to do with polyfills, but it seems not. Any help here would be greatly appreciated.

**Comment by asutula** [comment]
To clarify, this is a Nextjs 13 app with the experimental `app/` directory, but I'm making sure the component importing from the Biconomy (and therefore eccrypto) is a client component.

**Comment by jordan-mcrae** [comment]
+1, same issue with Nextjs 13

**Comment by asutula** [comment]
Nice @jordan-mcrae I'll try that asap. Thank you.

**Comment by chaitanyapotti** [comment]
this is fixed in the latest version. pls upgrade

**Comment by asutula** [comment]
Finally got around to testing this, and it works. Thanks!
