### ISSUE TITLE
Next.Js app can't compile because of @toruslab/eccrypto syntax error

### ISSUE THREAD

**Issue by ducmint864** [torusresearch/eccrypto#37]
## Description
Hi, I'm writing a simple NextJs program that use the lib 'react-moralis', and apparently, 'react-moralis' also utilizes @toruslab/eccrypto lib. When I compile my project with 'npm run build', it shows the syntax error related to @toruslab/eccrypto as following:
<img width="960" alt="image" src="https://github.com/torusresearch/eccrypto/assets/69887564/d0eb2e79-75c3-40c0-a773-e983d7662395">

## Context
1. NodeJs version: 18.16
2. Os: Ubuntu 22.04 (WSL)

## How to recreate the error
1. Init NextJs project: ``npx create-next-app@latest``
2. Edit the content /app/page.tsx as follow:
```javascript
import { useMoralis, useWeb3Contract } from 'react-moralis';
export default function Home() {
    const { enableWeb3, isWeb3Enabled } = useMoralis();
    return (
        <h1>Hi</h1>
    )
}
```
3. Edit the content of /app/layout.tsx as follow:
```javascript
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Header /> */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
```
4. Run command ``npm run build``

**Comment by mjafri118** [comment]
@ducmint864 have you found a fix to get going with this?

**Comment by ducmint864** [comment]
@mjafri118  Unfortunately no, I still don't know how to fix it til this day. I'm just a student so if this package doesn't work, Imma just move on. If you're having the same problem as I did, hope you find a solution for yourself.

**Comment by chaitanyapotti** [comment]
Should be solved now

**Comment by mjafri118** [comment]
> Should be solved now

Wich version introduced the fix?
